# Generated by Django 5.1.6 on 2025-02-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="resNet_model",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("model_accuracy", models.CharField(max_length=10)),
                ("model_name", models.CharField(max_length=10)),
                ("model_executed", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "resNet_model",
            },
        ),
        migrations.CreateModel(
            name="unet_model",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("model_accuracy", models.CharField(max_length=10)),
                ("model_name", models.CharField(max_length=10)),
                ("model_executed", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "unet_model",
            },
        ),
    ]
